a = int(input("Enter a number: "))
b = int(input("Enter another number: "))
print(f"The comparison of {a} and {b} is: {a == b}")
print(f"The comparison of {a} and {b} is: {a != b}")
print(f"The comparison of {a} and {b} is: {a > b}")
print(f"The comparison of {a} and {b} is: {a < b}")
print(f"The comparison of {a} and {b} is: {a >= b}")
print(f"The comparison of {a} and {b} is: {a <= b}")
